/**
 * Ship Roles — Into the Storm Chapter VII (pp.224-232).
 *
 * 22 roles across 4 ranks. Roles are command positions aboard a Rogue
 * Trader's vessel, distinct from a character's Career. Each carries a
 * mechanical benefit (typically a +X bonus to a specific Extended
 * Action from RT Core Ch.VIII) and lists the careers that may take it.
 *
 * `careers` lists keys from origin-path/careers.mjs. `null` means no
 * career restriction. Special restrictions (homeworld, exclusions) are
 * captured in `careerNotes`.
 */
export function shipRoleOptions() {
    return [
        // ============ RANK ONE — Lord-Captain ============
        {
            key: 'lordCaptain',
            label: 'Lord-Captain',
            rank: 1,
            careers: ['rogueTrader'],
            careerNotes: 'Rogue Trader only (unless GM rules otherwise).',
            skills: 'Command, Charm, Intimidate, Scholastic Lore (Tactica Imperialis).',
            benefit: '+10 bonus to the Hold Fast! Extended Action. If the Lord-Captain possesses Exceptional Leader, he may grant it to anyone aboard the ship once per Strategic Round as a Free Action, ignoring the normal restrictions.',
            description: 'A void-ship is a mighty fortress, its Captain upon the command throne the feudal lord who accepts pledges of allegiance and fealty from his advisors and crew. The Lord-Captain is the ultimate decision-maker on matters of strategy, void-law, and negotiation.',
            source: 'Into the Storm, p.225',
        },

        // ============ RANK TWO — Lord-Captain's seconds ============
        {
            key: 'firstOfficer',
            label: 'First Officer',
            rank: 2,
            careers: ['rogueTrader', 'archMilitant', 'explorator', 'missionary', 'navigator', 'seneschal', 'voidMaster', 'krootMercenary', 'orkFreebooter'],
            careerNotes: 'Any Career except Astropath Transcendent.',
            skills: 'Command, Secret Tongue (Rogue Trader), Intimidation.',
            benefit: 'Treats Command as a Trained Basic Skill when dealing with the crew. If the First Officer already possesses Command, he receives +5 on all Command Tests made aboard ship.',
            description: 'Though a Lord-Captain\'s power is absolute, his time and energy are finite. The First Officer speaks and acts with the full authority of his Lord-Captain.',
            source: 'Into the Storm, p.225',
        },
        {
            key: 'engineerPrime',
            label: 'Engineer Prime',
            rank: 2,
            careers: ['explorator', 'missionary', 'voidMaster'],
            careerNotes: 'Usually Explorator; also Missionary or Void-master.',
            skills: 'Tech-Use, Chem-Use, Common Lore (Machine Cult), Forbidden Lore (Adeptus Mechanicus).',
            benefit: '+10 bonus to the Emergency Repairs Extended Action.',
            description: 'The Engineer Prime directs the constant labour that sustains the ship\'s machine spirit, and is responsible for the void-ship\'s strength, resilience, and tech-secrets.',
            source: 'Into the Storm, p.225',
        },
        {
            key: 'highFactotum',
            label: 'High Factotum',
            rank: 2,
            careers: ['seneschal', 'missionary'],
            careerNotes: 'Usually Seneschal; also Missionary.',
            skills: 'Barter, Commerce, Evaluate.',
            benefit: 'Once per game session, may take up to 300 Achievement Points gathered toward the completion of one Endeavour and apply them to the completion of another.',
            description: 'A maestro of negotiations, compacts, endless records, bribes, threats, and the filling and emptying of great-holds. The High Factotum keeps the venture profitable.',
            source: 'Into the Storm, p.226',
        },

        // ============ RANK THREE — specialised command staff ============
        {
            key: 'masterAtArms',
            label: 'Master-at-Arms',
            rank: 3,
            careers: ['archMilitant', 'voidMaster'],
            careerNotes: 'Usually Arch-Militant; also Void-master.',
            skills: 'Command, Tech-Use, Intimidate, Scholastic Lore (Tactica Imperialis).',
            benefit: '+10 bonus to the Prepare to Repel Boarders! Extended Action.',
            description: 'Responsible for the ship\'s armed forces — security companies, boarding parties, the common crew armed, and any barracked regiments. Ensures loyalty, guards security, leads boarding actions.',
            source: 'Into the Storm, p.227',
        },
        {
            key: 'masterHelmsman',
            label: 'Master Helmsman',
            rank: 3,
            careers: ['voidMaster', 'explorator', 'archMilitant'],
            careerNotes: 'Usually Void-master; also Explorator or Arch-Militant.',
            skills: 'Pilot (Space Craft), Scholastic Lore (Astromancy), Common Lore (Koronus Expanse), Trade (Voidfarer).',
            benefit: '+10 bonus to the Evasive Manoeuvres Action.',
            description: 'Responsible for safely piloting the vast vessel through the myriad threats of the void of space.',
            source: 'Into the Storm, p.227',
        },
        {
            key: 'masterOfOrdnance',
            label: 'Master of Ordnance',
            rank: 3,
            careers: ['archMilitant', 'voidMaster'],
            careerNotes: 'Usually Arch-Militant; also Void-master.',
            skills: 'Command, Scholastic Lore (Tactica Imperialis), Trade (Voidfarer).',
            benefit: 'When firing ship weapons while benefiting from the Lock on Target Extended Action, adds an additional +5 bonus to the Ballistic Skill Test.',
            description: 'Pledges to keep the void-ship\'s weapons and fighting crew in the finest condition, and directs them to destroy foes at the Lord-Captain\'s order.',
            source: 'Into the Storm, p.227',
        },
        {
            key: 'masterOfEtherics',
            label: 'Master of Etherics',
            rank: 3,
            careers: ['voidMaster', 'archMilitant', 'explorator'],
            careerNotes: 'Usually Void-master; also Arch-Militant or Explorator.',
            skills: 'Scrutiny, Tech-Use, Trade (Voidfarer). Knowledge Skills to identify Components of an opposing vessel.',
            benefit: '+10 bonus to the Focused Augury Extended Action.',
            description: 'Responsible for the operation of the void-ship\'s auspex and vox systems. Without auspex a vessel is blind, and without vox it is deaf and mute.',
            source: 'Into the Storm, p.227',
        },
        {
            key: 'chiefChirurgeon',
            label: 'Chief Chirurgeon',
            rank: 3,
            careers: ['missionary', 'explorator', 'seneschal'],
            careerNotes: 'Usually Missionary or Explorator; also Seneschal.',
            skills: 'Medicae, Chem-Use, Scholastic Lore (Chymistry), Tech-Use, Trade (Technomat).',
            benefit: '+10 bonus to the Triage Extended Action.',
            description: 'Master of the void-ship\'s medicae wards and their staff. Maintains crew\'s ability to toil by warding off injury, disease, and sicknesses of the mind.',
            source: 'Into the Storm, p.228',
        },
        {
            key: 'masterOfWhispers',
            label: 'Master of Whispers',
            rank: 3,
            careers: ['seneschal', 'missionary'],
            careerNotes: 'Usually Seneschal; also Missionary.',
            skills: 'Inquiry, Deceive, Interrogation, Scrutiny.',
            benefit: '+10 bonus to the Disinformation Extended Action.',
            description: 'Seeks out and purges the crooked timbers and weak spars in the Rogue Trader\'s crew. His agents hunt for the same elements in rival Rogue Trader missions for the purpose of advantage and deception.',
            source: 'Into the Storm, p.228',
        },
        {
            key: 'choirMasterTelepathica',
            label: 'Choir-master Telepathica',
            rank: 3,
            careers: ['astropathTranscendent'],
            careerNotes: 'Astropath Transcendent only.',
            skills: 'Psyniscience, Forbidden Lore (The Warp), Command.',
            benefit: 'May increase the range of his Astropathic Signals by one step (see Table 6-5: Astropathic Signals in Rogue Trader).',
            description: 'When the etheric voices of the choir are united by a single will, they combine into a psychic harmony capable of touching minds half a galaxy away. The Choir-master directs that harmony.',
            source: 'Into the Storm, p.228',
        },
        {
            key: 'warpGuide',
            label: 'Warp Guide (Navigator Primaris)',
            rank: 3,
            careers: ['navigator'],
            careerNotes: 'Navigator only.',
            skills: 'Navigation (Warp), Trade (Astrographer), Scholastic Lore (Astromancy), Forbidden Lore (The Warp).',
            benefit: '+5 bonus to the Navigation (Warp) Skill for purposes of steering the ship through the Warp.',
            description: 'Wholly responsible for steering the vessel through the treacherous tides of the Empyrean. A single mistake and terrible daemons of the Empyreal spaces will consume the vessel and all aboard it.',
            source: 'Into the Storm, p.228',
        },

        // ============ RANK FOUR — day-to-day operations ============
        {
            key: 'shipsConfessor',
            label: 'Ship\'s Confessor',
            rank: 4,
            careers: ['missionary', 'explorator', 'seneschal'],
            careerNotes: 'Usually Missionary; also Explorator or Seneschal.',
            skills: 'Scholastic Lore (Imperial Creed), Common Lore (Ecclesiarchy, Imperial Creed), Charm, Intimidate.',
            benefit: '+10 bonus to the Put your backs into it! Extended Action.',
            description: 'The uppermost hierarch of shrines and Clerics aboard the vessel, responsible for their scriptural purity and the spiritual well-being of all aboard.',
            source: 'Into the Storm, p.229',
        },
        {
            key: 'drivesmaster',
            label: 'Drivesmaster',
            rank: 4,
            careers: ['explorator'],
            careerNotes: 'Explorators only.',
            skills: 'Tech-Use, Forbidden Lore (Archeotech), Pilot (Space Craft).',
            benefit: '+10 bonus to the Flank Speed Extended Action.',
            description: 'In charge of monitoring and maintaining the roaring plasma drives that form the heart of the ship.',
            source: 'Into the Storm, p.229',
        },
        {
            key: 'omnissianicCongregator',
            label: 'Omnissianic Congregator',
            rank: 4,
            careers: ['explorator'],
            careerNotes: 'Explorators or any character with the Forge World Home World option.',
            skills: 'Tech-Use, Forbidden Lore (Adeptus Mechanicus), Trade (Technomat).',
            benefit: '+10 bonus to the Aid the Machine Spirit Extended Action.',
            description: 'Guides the tech-priests and other crew versed in technoarcane ritual in the maintenance rites and algorithmic prayers that appease the ship\'s machine spirit.',
            source: 'Into the Storm, p.229',
        },
        {
            key: 'chiefBosun',
            label: 'Chief Bosun',
            rank: 4,
            careers: ['archMilitant', 'missionary', 'seneschal', 'voidMaster'],
            careerNotes: 'Arch-militants, Missionaries, Seneschals, and Void-masters.',
            skills: 'Command, Intimidation, Trade (Shipwright).',
            benefit: 'Provides a +5 bonus to the ship\'s NPC Crew Rating. As long as the Chief Bosun is aboard, Command Tests involving the ship\'s crew suffer no penalties for reduced Morale.',
            description: 'Keeps crew skills sharp through regular drills and practice sessions, and serves as the enforcer of discipline aboard the vessel.',
            source: 'Into the Storm, p.230',
        },
        {
            key: 'infernusMaster',
            label: 'Infernus Master',
            rank: 4,
            careers: ['archMilitant', 'missionary', 'seneschal', 'voidMaster', 'krootMercenary', 'orkFreebooter'],
            careerNotes: 'Any except Rogue Trader, Astropath Transcendent, Explorator, or Navigator.',
            skills: 'Command, Intimidate, Search.',
            benefit: '+20 bonus to all Command Tests made to combat shipboard fires.',
            description: 'Keeps order and minimises damage during conflagrations — organising bucket chains, directing evacuations, and commanding damage control crews brave enough to combat even the deadliest plasma flares.',
            source: 'Into the Storm, p.230',
        },
        {
            key: 'twistcatcher',
            label: 'Twistcatcher',
            rank: 4,
            careers: ['archMilitant', 'astropathTranscendent', 'explorator', 'missionary', 'navigator', 'seneschal', 'voidMaster', 'krootMercenary', 'orkFreebooter'],
            careerNotes: 'Most often Arch-militants and Missionaries; any character except the Rogue Trader may take this Role.',
            skills: 'Forbidden Lore (Mutants), Secret Tongue (Underdecks), Tracking.',
            benefit: 'Immediately after Starship Combat, may raid the lower decks, replacing dead crew with mutant slaves: the ship regains 1d5 Crew Population but loses 1 Crew Morale.',
            description: 'Keeps the ship\'s mutant population in check, and in times of dire need presses these malformed wastrels into service for the good of the human crew.',
            source: 'Into the Storm, p.230',
        },
        {
            key: 'masterOfTheVox',
            label: 'Master of the Vox',
            rank: 4,
            careers: ['astropathTranscendent', 'seneschal', 'voidMaster'],
            careerNotes: 'Astropath Transcendent, Seneschal, or Void-master.',
            skills: 'Ciphers (Rogue Trader), Secret Tongue (Rogue Trader), Trade (Cryptographer).',
            benefit: '+20 bonus to the Jam Communications Extended Action.',
            description: 'Keeps all channels of communication clear and all vox-casters functioning at peak efficiency, handling the endless stream of vox traffic that passes through a void-ship\'s command deck.',
            source: 'Into the Storm, p.231',
        },
        {
            key: 'purser',
            label: 'Purser',
            rank: 4,
            careers: ['seneschal'],
            careerNotes: 'Seneschal only.',
            skills: 'Barter, Commerce, Evaluate.',
            benefit: 'When replenishing Morale by spending Achievement Points, the Purser only has to spend 25 (not 50), and may always make a Routine (+20) Barter Test instead of a Charm Test.',
            description: 'Shuffles wealth between investments and expenses on a daily basis, balances the books, and rations payment to the crew — for which he is loved and hated in turn.',
            source: 'Into the Storm, p.231',
        },
        {
            key: 'cartoArtifex',
            label: 'Carto-artifex',
            rank: 4,
            careers: ['seneschal', 'navigator', 'explorator'],
            careerNotes: 'Seneschals, Navigators, Explorators, and other Explorers with a scholarly bent.',
            skills: 'Trade (Astrographer), Navigation (Stellar), Navigation (Warp), Forbidden Lore (Navigators).',
            benefit: '+10 bonus to all Awareness and Perception Tests made during Warp Navigation and when detecting stellar phenomena.',
            description: 'Master of charts and hololithic maps, charged with finding safe routes and circumventing the dangers of the void and the warp.',
            source: 'Into the Storm, p.231',
        },
        {
            key: 'shipsSteward',
            label: 'Ship\'s Steward',
            rank: 4,
            careers: ['seneschal', 'voidMaster'],
            careerNotes: 'Seneschals, Void-masters, or any character with the Void Born Home World option.',
            skills: 'Blather, Survival.',
            benefit: 'Doubles the effective provisions of a craft, allowing it to function for up to a year before the crew suffers the consequences of long voyages.',
            description: 'Takes charge of the vast stocks of food, water, and air upon which a crew depends, monitoring and rationing them lest wanton consumption and theft lead to a crippling shortage.',
            source: 'Into the Storm, p.231',
        },
    ];
}

/** Look up one role by key. Returns undefined for an unknown key. */
export function getShipRole(key) {
    if (!key) return undefined;
    return shipRoleOptions().find(r => r.key === key);
}
